### ISSUE TITLE
Infinite looping in `repeat_until_tightened` when using `pydiff.diff`

### ISSUE THREAD

**Issue by martijnthe** [trailofbits/graphtage#82]
Hi! Thanks for creating this library!
I've been experimenting with it a bit today. It's pretty awesome.

I noticed that sometimes `pydiff.diff` gets stuck into an infinite loop.
I stepped through the code a bit and it's stuck in `repeat_until_tightened`, with bounds that stay the same (`[0, 18]`) and don't become "definitive". I don't understand the algorithms (yet), so I wasn't sure what the problem is beyond this.

Here's the smallest repro case I could come up with:

```
import dataclasses
import graphtage


@dataclasses.dataclass
class Thing:
    foo: str


def main() -> None:
    d = graphtage.pydiff.diff([Thing("ok")], [Thing("bad")])

    # Interestingly, this runs fine:
    # d = graphtage.pydiff.diff(Thing("ok"), Thing("bad"))

    with graphtage.printer.DEFAULT_PRINTER as printer:
        graphtage.pydiff.PyDiffFormatter.DEFAULT_INSTANCE.print(printer, d)


if __name__ == "__main__":
    main()
```

Let me know if there's anything I can help to debug this!

**Comment by ESultanik** [comment]
Thanks @martijnthe, this was a bug limited to the new python object diffing feature. It has been fixed and will be included in the next release.

**Comment by martijnthe** [comment]
Thanks for the quick fix @ESultanik !
